version: "3"

services:
  web:
    build: ./server
    container_name: playground-web
    volumes:
      - ./server/app:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:8000

  ruby:
    build: ./docker/ruby
    container_name: playground-ruby
    volumes:
      - ./server/app/share:/user/share
    tty: true

  rust:
    build: ./docker/rust
    container_name: playground-rust
    volumes:
      - ./server/app/share:/user/share
    tty: true
